animalList = ["pig","chicken","goat","donkey","horse","cow","bull","elephant","turkey","tiger"]
print(animalList[0])
print(animalList[6])
print(animalList[2:5])
print(animalList[0:6:2])
print(animalList[0])
print(animalList[-1])
print(animalList[-2])
print(animalList[:])
print(animalList[:4])
print(animalList[::-1])
